CC = gcc
CFLAGS=-Wall -Wextra -fPIC -xc -g -std=gnu99

quicksort_random_and_median.o: ../sort_helpers/sort_helpers.o

clean:
		rm -f quicksort_random_and_median.o

rebuild: clean quicksort_random_and_median.o
	

